### ISSUE TITLE
Is the heatmap at 95th percentile applicable to scRNA-seq data?

### ISSUE THREAD

**Issue by levinhein** [cxli233/FriendsDontLetFriends#1]
Hello. Is heatmap plotting to overcome outlier bias at 95th percentile visualization applicable to scRNA-seq heatmaps?

![image](https://user-images.githubusercontent.com/68268222/179673417-a36067fc-d496-40d2-8e44-f59477b18018.png)

![image](https://user-images.githubusercontent.com/68268222/179674594-503e040d-c732-4f2a-95c4-c8633f08b3af.png)

**Comment by cxli233** [comment]
Yes, clipping heat map color scale at 5th to 95th percentiles is applicable to scRNA-seq data, but there is different problem here. 

I've done a fair amount of scRNA-seq with Seurat but I don't have experience with the package you are using. The violin plot has y axis going from 0 to 4; the heat map has color scale going from -1 to 1. Is the color scale log transformed? Is the color scale showing some sort of z-score? 

I would suggest using DotPlot() from Seurat to make the heat map. In addition to using the color scale to represent average expression, it also calculates % of cell with non-0 expression. I suggest this because clusters 1 and 2 have a fair % of drop-outs (cells where the transcript is not detected), which might be the reason the average expression is lower than what is expected from the violin plot.
